site = window.site || {};
site.data = site.data || {};

site.data.stairs = [
    {src: "img/stairs/stairs01.jpg", thumb: "img/stairs/thumbs/stairs01.jpg"},
    //{src: "img/stairs/stairs02.jpg", thumb: "img/stairs/thumbs/stairs02.jpg"},
    {src: "img/stairs/stairs03.jpg", thumb: "img/stairs/thumbs/stairs03.jpg"},
    {src: "img/stairs/stairs04.jpg", thumb: "img/stairs/thumbs/stairs04.jpg"},
    {src: "img/stairs/stairs05.jpg", thumb: "img/stairs/thumbs/stairs05.jpg"},
    {src: "img/stairs/stairs06.jpg", thumb: "img/stairs/thumbs/stairs06.jpg"},
    {src: "img/stairs/stairs07.jpg", thumb: "img/stairs/thumbs/stairs07.jpg"},
    {src: "img/stairs/stairs08.jpg", thumb: "img/stairs/thumbs/stairs08.jpg"},
    {src: "img/stairs/stairs09.jpg", thumb: "img/stairs/thumbs/stairs09.jpg"},
    {src: "img/stairs/stairs10.jpg", thumb: "img/stairs/thumbs/stairs10.jpg"},
    {src: "img/stairs/stairs11.jpg", thumb: "img/stairs/thumbs/stairs11.jpg"},
    //{src: "img/stairs/stairs12.jpg", thumb: "img/stairs/thumbs/stairs12.jpg"},
    //{src: "img/stairs/stairs13.jpg", thumb: "img/stairs/thumbs/stairs13.jpg"},
    {src: "img/stairs/stairs14.jpg", thumb: "img/stairs/thumbs/stairs14.jpg"},
    {src: "img/stairs/stairs15.jpg", thumb: "img/stairs/thumbs/stairs15.jpg"},
    {src: "img/stairs/stairs16.jpg", thumb: "img/stairs/thumbs/stairs16.jpg"},
    {src: "img/stairs/stairs17.jpg", thumb: "img/stairs/thumbs/stairs17.jpg"},
    {src: "img/stairs/stairs18.jpg", thumb: "img/stairs/thumbs/stairs18.jpg"},
    {src: "img/stairs/stairs19.jpg", thumb: "img/stairs/thumbs/stairs19.jpg"},
    {src: "img/stairs/stairs20.jpg", thumb: "img/stairs/thumbs/stairs20.jpg"},
    //{src: "img/stairs/stairs21.jpg", thumb: "img/stairs/thumbs/stairs21.jpg"},
    //{src: "img/stairs/stairs22.jpg", thumb: "img/stairs/thumbs/stairs22.jpg"},
    {src: "img/stairs/stairs23.jpg", thumb: "img/stairs/thumbs/stairs23.jpg"},
    {src: "img/stairs/stairs24.jpg", thumb: "img/stairs/thumbs/stairs24.jpg"},
    {src: "img/stairs/stairs25.jpg", thumb: "img/stairs/thumbs/stairs25.jpg"},
    {src: "img/stairs/stairs26.jpg", thumb: "img/stairs/thumbs/stairs26.jpg"},
    //{src: "img/stairs/stairs27.jpg", thumb: "img/stairs/thumbs/stairs27.jpg"},
    {src: "img/stairs/stairs28.jpg", thumb: "img/stairs/thumbs/stairs28.jpg"},
    {src: "img/stairs/stairs29.jpg", thumb: "img/stairs/thumbs/stairs29.jpg"},
    {src: "img/stairs/stairs30.jpg", thumb: "img/stairs/thumbs/stairs30.jpg"},
    {src: "img/stairs/stairs31.jpg", thumb: "img/stairs/thumbs/stairs31.jpg"},
    {src: "img/stairs/stairs32.jpg", thumb: "img/stairs/thumbs/stairs32.jpg"},
    {src: "img/stairs/stairs33.jpg", thumb: "img/stairs/thumbs/stairs33.jpg"},
    {src: "img/stairs/stairs34.jpg", thumb: "img/stairs/thumbs/stairs34.jpg"},
    {src: "img/stairs/stairs35.jpg", thumb: "img/stairs/thumbs/stairs35.jpg"},
    //{src: "img/stairs/stairs36.jpg", thumb: "img/stairs/thumbs/stairs36.jpg"},
    {src: "img/stairs/stairs37.jpg", thumb: "img/stairs/thumbs/stairs37.jpg"},
    {src: "img/stairs/stairs38.jpg", thumb: "img/stairs/thumbs/stairs38.jpg"},
    {src: "img/stairs/stairs39.jpg", thumb: "img/stairs/thumbs/stairs39.jpg"},
    {src: "img/stairs/stairs40.jpg", thumb: "img/stairs/thumbs/stairs40.jpg"},
    {src: "img/stairs/stairs41.jpg", thumb: "img/stairs/thumbs/stairs41.jpg"},
    {src: "img/stairs/stairs42.jpg", thumb: "img/stairs/thumbs/stairs42.jpg"},
    {src: "img/stairs/stairs43.jpg", thumb: "img/stairs/thumbs/stairs43.jpg"},
];